# Generated by Django 3.0.8 on 2020-07-20 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_closed_comment_listing_watchlist'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.IntegerField()),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('pic', models.CharField(blank=True, default=None, max_length=64, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='listing_id',
        ),
    ]
