# Generated by Django 3.0.8 on 2020-07-22 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20200721_0225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='time',
        ),
    ]
