# Generated by Django 3.0.8 on 2020-07-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_bid_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Closed',
            new_name='Closedbid',
        ),
    ]
